import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const siteDir = path.join(root, "ui_kits", "website");
const outDir = path.join(siteDir, "dist");
const babelUrl = "https://unpkg.com/@babel/standalone@7.29.0/babel.min.js";

const bundles = [
  {
    outFile: path.join(outDir, "site.js"),
    sources: [
      "tweaks-panel.jsx",
      "Tweaks.jsx",
      "HeroGraphics.jsx",
      "Header.jsx",
      "Features.jsx",
      "Pricing.jsx",
      "Sections.jsx",
      "Footer.jsx",
      "App.jsx",
    ],
  },
  {
    outFile: path.join(outDir, "secure-infrastructure.js"),
    sources: ["Footer.jsx", "services/serviceTokens.jsx", "services/SecureInfrastructure.jsx", "services/SecureInfrastructureApp.jsx"],
  },
  {
    outFile: path.join(outDir, "security-architecture.js"),
    sources: ["Footer.jsx", "services/serviceTokens.jsx", "services/SecurityArchitecture.jsx", "services/SecurityArchitectureApp.jsx"],
  },
  {
    outFile: path.join(outDir, "managed-detection-response.js"),
    sources: ["Footer.jsx", "services/serviceTokens.jsx", "services/ManagedDetectionResponse.jsx", "services/ManagedDetectionResponseApp.jsx"],
  },
];

async function loadBabel() {
  const response = await fetch(babelUrl);
  if (!response.ok) {
    throw new Error(`Unable to download Babel: ${response.status} ${response.statusText}`);
  }

  const code = await response.text();
  const context = { window: {}, self: {}, console };
  context.globalThis = context;
  vm.createContext(context);
  vm.runInContext(code, context, { filename: "babel-standalone.js" });

  return context.Babel || context.window.Babel;
}

const banner = [
  "/*",
  " * Generated by tools/build-website.mjs.",
  " * Edit the JSX source files in ui_kits/website, then rebuild this bundle.",
  " */",
  "",
].join("\n");

const Babel = await loadBabel();
fs.mkdirSync(outDir, { recursive: true });

for (const bundle of bundles) {
  const input = bundle.sources
    .map((file) => {
      const fullPath = path.join(siteDir, file);
      return `\n/* Source: ${file} */\n${fs.readFileSync(fullPath, "utf8")}\n`;
    })
    .join("\n");

  const output = Babel.transform(input, {
    presets: [["react", { runtime: "classic" }]],
    sourceType: "script",
    comments: false,
    compact: false,
  }).code;

  fs.writeFileSync(bundle.outFile, `${banner}${output}\n`);
  console.log(`Built ${path.relative(root, bundle.outFile)} from ${bundle.sources.length} JSX files.`);
}
