import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const siteDir = path.join(root, "ui_kits", "website");
const outDir = path.join(siteDir, "dist");
const outFile = path.join(outDir, "site.js");
const babelUrl = "https://unpkg.com/@babel/standalone@7.29.0/babel.min.js";

const sources = [
  "tweaks-panel.jsx",
  "Tweaks.jsx",
  "HeroGraphics.jsx",
  "Header.jsx",
  "Features.jsx",
  "Pricing.jsx",
  "Sections.jsx",
  "Footer.jsx",
  "App.jsx",
];

async function loadBabel() {
  const response = await fetch(babelUrl);
  if (!response.ok) {
    throw new Error(`Unable to download Babel: ${response.status} ${response.statusText}`);
  }

  const code = await response.text();
  const context = { window: {}, self: {}, console };
  context.globalThis = context;
  vm.createContext(context);
  vm.runInContext(code, context, { filename: "babel-standalone.js" });

  return context.Babel || context.window.Babel;
}

const banner = [
  "/*",
  " * Generated by tools/build-website.mjs.",
  " * Edit the JSX source files in ui_kits/website, then rebuild this bundle.",
  " */",
  "",
].join("\n");

const input = sources
  .map((file) => {
    const fullPath = path.join(siteDir, file);
    return `\n/* Source: ${file} */\n${fs.readFileSync(fullPath, "utf8")}\n`;
  })
  .join("\n");

const Babel = await loadBabel();
const output = Babel.transform(input, {
  presets: [["react", { runtime: "classic" }]],
  sourceType: "script",
  comments: false,
  compact: false,
}).code;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, `${banner}${output}\n`);
console.log(`Built ${path.relative(root, outFile)} from ${sources.length} JSX files.`);
